A = int(input("Give me the first number:"))
B = int(input("Give me the second number:"))
print ("Thank you!")
print (f"{A} + {B}", "=", end=' ')
print (int(A + B))
print (f"{A}-{B}", "=", end="")
print (int(A - B))
print (f"{A} / {B}", "=", end="")
print (int(A / B))
print (f"{A} * {B}", "=", end="")
print (int(A * B))